# EXAMPLE:
# git tag 0.7.12-rc.1
# git push origin main
# git push origin 0.7.12-rc.1
# .github/workflows/pre-release.yml
name: Build and Release (Pre-Release)

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+'  # Pre-release tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Create release"
        uses: ./.github/actions/build-release
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Prepare release notes
        id: prepare_notes
        run: |
          echo "## Old-School Essentials Pre-Release" > release_notes.txt
          echo "" >> release_notes.txt
          echo "This is a pre-release version of Old-School Essentials." >> release_notes.txt
          echo "To install manually, use this URL:" >> release_notes.txt
          echo "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.json" >> release_notes.txt

      - name: Create GitHub pre-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ github.event.release.tag_name }}
          name: "Pre-Release ${{ github.event.release.tag_name }}"
          draft: false
          prerelease: true
          artifacts: "./system.json, ./system.zip"
          bodyfile: release_notes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
